# Example Name.com DDNS configuration

[core]
# url = "https://api.name.com/"
username = "example"
key = "40-char Name.com API key"
# Timeout in seconds, 0 is no timeout
# timeout = 30
# Update interval in minutes
# interval = 60

[[records]]
host = "ddns"
zone = "example.com"
type = "A"
ttl = 300
# "global" for an address as seen from the internet
# "local" for an address on the NIC
method = "global"
# Ignored if method is "global"
# On Windows, this is the GUID of the adapter, can be found in the registry at
# /HKEY_LOCAL_MACHINE/SOFTWARE/Microsoft/WindowsNT/CurrentVersion/NetworkCards/*/ServiceName
interface = "en0"

[[records]]
host = "ddns"
zone = "example.com"
type = "AAAA"
ttl = 300
method = "local"
interface = "en0"
